<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Potatos-Mac.local" name="TestCases.UpdatePasswordTest" tests="4" failures="1" timestamp="2021-02-05T18:57:59 WIB" time="9.071" errors="0">
  <testcase name="signIn" time="3.551" classname="TestCases.UpdatePasswordTest"/>
  <testcase name="F01_UpdatePasswordWithIncorrectCurrentPassword" time="2.771" classname="TestCases.UpdatePasswordTest"/>
  <testcase name="F02_UpdatePasswordWithNewPasswordAndCoPasswordAreDifferent" time="1.992" classname="TestCases.UpdatePasswordTest"/>
  <testcase name="F03_UpdatePasswordWithCorrectInput" time="0.757" classname="TestCases.UpdatePasswordTest">
    <failure type="java.lang.AssertionError" message="password is not updated did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: password is not updated did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at TestCases.UpdatePasswordTest.F03_UpdatePasswordWithCorrectInput(UpdatePasswordTest.java:111)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- F03_UpdatePasswordWithCorrectInput -->
</testsuite> <!-- TestCases.UpdatePasswordTest -->
